### ISSUE TITLE
1-CreateHomePage

### ISSUE THREAD

**Issue by RawrBear** [RawrBear/theleftbehind#2]
**Description:**
These are the items that need to be on the home page for it to be considered ready.

**Tasks**
- [ ] Header menu
- [ ] Hero section
- [ ] Intro blurb explaining the disappearing
- [ ] Timeline explaining the tribulation in order
- [ ] Give gospel
- [ ] Video messages
- [ ] Show what comes after the tribulation
