### ISSUE TITLE
4-CreateTimelineComponent

### ISSUE THREAD

**Issue by RawrBear** [RawrBear/theleftbehind#5]
**Description**
This will be the timeline showing each step of the tribulation and what they can expect to see. I'm thinking that each of the content boxes should animate in, probably a fade and subtle up movement.

**Tasks**
- [x] Add the line and circles
- [x] Add the content boxes
- [ ] Add the content / research the steps
- [ ] Animate
- [ ] Responsive
